name: Run Autoupdate (manual)

on:
  workflow_dispatch:

jobs:
  run-autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run autoupdate once
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENABLE_AUTOUPDATE: 'false'
        run: |
          go mod tidy
          go run main.go --autoupdate
