name: Run Autoupdate (manual)

on:
  workflow_dispatch:

jobs:
  run-autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run autoupdate once
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENABLE_AUTOUPDATE: 'false'
          # Optional: set these secrets in the repository settings to allow the
          # workflow to use the real GitHubUpdater (it will create issues).
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
        run: |
          echo "Running autoupdater (manual). If GITHUB_TOKEN/GITHUB_REPO are set, real issues may be created."
          go mod tidy
          go run main.go --autoupdate
